/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import sample.Application;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Application classUnderTest = new Application();
        assertNotNull("app should have a greeting");
    }
}
